version: '3'
silent: true

vars:
  ROOT_DIR:
    sh: git rev-parse --show-toplevel

includes:
  bun: ~/.local/share/wave/templates/Taskfile.bun.yml
  conv: ~/.local/share/wave/templates/Taskfile.pkl.yml
  docker: ~/.local/share/wave/templates/Taskfile.docker.yml
  go: ~/.local/share/wave/templates/Taskfile.go.yml
  log: ~/.local/share/wave/templates/Taskfile.log.yml
  dev: 
    taskfile: .taskfiles/Dev.yml
    flatten: true
    dir: .

tasks:
  default:
    cmds:
      - task -l
    silent: true
